name: pythia-metpy-tutorial
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - geopandas
  - jupyterlab
  - matplotlib
  - metpy=1.2
  - netCDF4
  - numpy
  - pandas
  - pint
  - scipy
  - xarray
